name: Update Secure Data JSON

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Fetch Data from Cloudflare
        run: |
          curl -s "https://spring-voice-2488.jahangir339932.workers.dev/data.json" -o data.json

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto/Manual update tokenized streams" && git push)
