name: Update tv.json Data

on:
  schedule:
    # প্রতি ১ ঘণ্টা পর পর অটোমেটিক চলবে
    - cron: '0 * * * *'
  # GitHub Actions ট্যাব থেকে ইচ্ছামতো ম্যানুয়ালি রান করার জন্য
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch and Update tv.json from Cloudflare Worker
        run: |
          # ক্লাউডফ্লেয়ার ওয়ার্কার লিঙ্ক থেকে রেসপন্স নিয়ে tv.json ফাইলে সংরক্ষণ করবে
          curl -s -H "Referer: https://sobujaka.github.io/" "https://broad-darkness-2d66.jahangir339932.workers.dev/" -o tv.json

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add tv.json
          git diff-index --quiet HEAD || git commit -m "Auto/Manual update tv.json from Cloudflare Worker"
          git push
