name: Update tv.json Data

on:
  schedule:
    # প্রতি ১ ঘণ্টা পর পর স্বয়ংক্রিয়ভাবে চলবে
    - cron: '0 * * * *'
  # ম্যানুয়ালি যেকোনো সময় 'Run workflow' চাপ দিয়ে আপডেট করার জন্য
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Data from Cloudflare Worker and Save to tv.json
        run: |
          # ক্লাউডফ্লেয়ার ওয়ার্কারের সঠিক ইউআরএল থেকে ডেটা টেনে tv.json ফাইলে রাখবে
          curl -sL -H "User-Agent: github-actions" "https://broad-darkness-2d66.jahangir339932.workers.dev/" -o tv.json

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add tv.json
          git diff-index --quiet HEAD || git commit -m "Auto/Manual update tv.json from Cloudflare Worker"
          git push
