name: Update Secure Data JSON

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,6,12,18 * * *'

jobs:
  update-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Fetch Data from Cloudflare
        run: |
          curl -sL "https://cool-band-c2df.jahangir339932.workers.dev" -o data.json

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update json data" && git push)
